Fix Kamailio dispatcher module - switch to Debian base
Issue: Alpine kamailio package doesn't include dispatcher module
Solution: Use Debian bullseye with kamailio-extra-modules

Error was:
  ERROR: could not find module <dispatcher> in /usr/lib/kamailio/modules

Fix:
  - Changed FROM alpine:3.18 to debian:bullseye-slim
  - Added kamailio-extra-modules package (includes dispatcher)
  - Includes all required modules for SIP load balancing

Now dispatcher module will be available for load balancing